service: auth-server

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - httpApi:
          path: /api/get-auth-url
          method: get

  getAccessToken:
    handler: handler.getAccessToken
    events:
      - httpApi:
          path: /api/token/{code}
          method: get

  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - httpApi:
          path: /api/get-events/{access_token}
          method: get
