service: auth-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    description: "Generate Google OAuth authorization URL"
    events:
      - http:
          path: api/get-auth-url
          method: get
          cors: true
  getAccessToken:
    handler: handler.getAccessToken
    description: "Exchange authorization code for access token"
    events:
      - http:
          path: api/token/{code}
          method: get
          cors: true
  getCalendarEvents:
    handler: handler.getCalendarEvents
    description: "Get calendar events using access token"
    events:
      - http:
          path: api/get-events/{access_token}
          method: get
          cors: true